# Mapping
projectName: 08-22-mbarq-mapping
dataDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/mapping_data
outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/08_22
samples: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/08_22/mbarq-mapping_sample.csv

## General settings
fq_fwd: _1.fq.gz
fq_rvr: _2.fq.gz
sanitise_name: true
name_delimiter: _
name_index: 3
merge_replicates: false # if set to false, 'sample' in sample.csv has to be a unique sample identifier
tn: B17N13GTGTATAAGAGACAG

#Preprocessing
qc: PE
mink: 11
trimq: 14 # 37
mapq: 20
minlen: 45
adapters: 'adapters/adapters.fa'
phix: 'adapters/phix174_ill.ref.fa.gz'
fastqc: no

## References
genome: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/SL1344/ncbi-genomes-2021-08-25/GCA_000210855.2_ASM21085v2_genomic.fna
gff: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/SL1344/ncbi-genomes-2021-08-25/GCA_000210855.2_ASM21085v2_genomic.gff

map_filter: 0

multiplex_codes: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/metadata/multiplex_codes.txt
controlFile: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/metadata/controls.txt


# KEGG

kegg_dmd: /nfs/nas22/fs2202/biol_micro_sunagawa/Projects/PAN/GENERAL_METAGT_ANALYSIS_PAN/data/resources/soft/kegg_annotation/kegg_db/kegg/kegg_for_prokka-with_ko.dmnd
kegg_ko: /nfs/nas22/fs2202/biol_micro_sunagawa/Projects/PAN/GENERAL_METAGT_ANALYSIS_PAN/data/resources/soft/kegg_annotation/kegg_db/kegg/ko
