# Counting
projectName: 08-22-rbseq-all
dataDir: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/Projects_NCCR/hardt/nguyenb/tnseq/scratch/manuscript_data/wetmore_2015
metaDir: ''
outDir: ''
samples: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/Projects_NCCR/hardt/nguyenb/tnseq/scratch/manuscript_data/wetmore_2015/barseq_samples.csv
mappingDir: ''
attribute: Name


## General settings
fq_fwd: _1.fq.gz
fq_rvr: _2.fq.gz
sanitise_name: true
name_delimiter: _
name_index: 1
merge_replicates: false # if set to false, 'sample' in sample.csv has to be a unique sample identifier
tn: GACCTGCAGCGTACGB20

#Preprocessing
qc: SE
mink: 11
trimq: 14 # 37
mapq: 20
minlen: 45
adapters: 'adapters/adapters.fa'
phix: 'adapters/phix174_ill.ref.fa.gz'
fastqc: no

## References
genome:
gff:

map_filter: 0

multiplex_codes:



# KEGG

kegg_dmd: /nfs/nas22/fs2202/biol_micro_sunagawa/Projects/PAN/GENERAL_METAGT_ANALYSIS_PAN/data/resources/soft/kegg_annotation/kegg_db/kegg/kegg_for_prokka-with_ko.dmnd
kegg_ko: /nfs/nas22/fs2202/biol_micro_sunagawa/Projects/PAN/GENERAL_METAGT_ANALYSIS_PAN/data/resources/soft/kegg_annotation/kegg_db/kegg/ko

## Counting
#dataDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/raw
#metaDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/metadata
#outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/08_21
#sampleFile: configs/samples.txt
#

# Analysis

treatmentColumn:
baseline:
controlStrains:
sampleData:
