# Mapping
projectName: 06-23-mbarq-mapping
dataDir: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/lifeer/28_06_2023_rerunning_mbarq/data
outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/final_maps
samples: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/final_maps/samples.csv

## General settings
fq_fwd: .1.fq.gz
fq_rvr: .2.fq.gz
sanitise_name: false
name_delimiter: _
name_index: 3
merge_replicates: false # if set to false, 'sample' in sample.csv has to be a unique sample identifier
tn: B17N13GTGTATAAGAGACAG
filter_low_counts: 50

#Preprocessing
qc: PE
mink: 11
trimq: 14 # 37
mapq: 20
minlen: 45
adapters: 'adapters/adapters.fa'
phix: 'adapters/phix174_ill.ref.fa.gz'
fastqc: no
se: 
merged:
unimode:
assembler:

## References
genome: /nfs/nas22/fs2202/biol_micro_sunagawa/Projects/PAN/REFERENCE_GENOMES_PAN/data/raw/GCA_000210855/GCA_000210855.2/GCA_000210855.2_ASM21085v2_genomic.fna
gff: /nfs/nas22/fs2202/biol_micro_sunagawa/Projects/PAN/REFERENCE_GENOMES_PAN/data/raw/GCA_000210855/GCA_000210855.2/GCA_000210855.2.gff3

map_filter: 50
normMethod:


multiplex_codes: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/metadata/multiplex_codes.txt
controlStrains: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/lifeer/28_06_2023_rerunning_mbarq/controls.txt
baseline:
treatment_col:

# Analysis
sampleData: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/Projects_NCCR/hardt/nguyenb/tnseq/scratch/08_22/14-04-22-sample-data.csv


# KEGG

kegg_dmd: /nfs/nas22/fs2202/biol_micro_sunagawa/Projects/PAN/GENERAL_METAGT_ANALYSIS_PAN/data/resources/soft/kegg_annotation/kegg_db/kegg/kegg_for_prokka-with_ko.dmnd
kegg_ko: /nfs/nas22/fs2202/biol_micro_sunagawa/Projects/PAN/GENERAL_METAGT_ANALYSIS_PAN/data/resources/soft/kegg_annotation/kegg_db/kegg/ko
