---
title: "R Notebook"
author: ansintsova
date: 06.09.21
output: html_notebook
---

```{r}
BiocManager::install("fgsea")
```
```{r}
#install.packages("data.table")        # install it
library(data.table)
library(fgsea)
library(ggplot2)
```
```{r}
data(examplePathways) # list of pathways
data(exampleRanks) # vector of gene ranks
set.seed(42)
fgseaRes <- fgsea(pathways = examplePathways,
                  stats    = exampleRanks,
                  minSize  = 15,
                  eps      = 0.0,
                  maxSize  = 500)

```


Take the final results,
1. find median z-score, rank by z-score
2. rank by p.adj, take median

```{r}
df <-read_csv("data/27_07_results_and_figures/final_results/26-07-final-results.csv" )

```


```{r}
ranked <- df %>% mutate(dir_change = ifelse(`z-score`<0, -1,1), rank=-1*log10(zscore_padj)*dir_change)
```

```{r}
ranked <- df %>% group_by(gene, day) %>% summarise(rankMed = median(`z-score`, na.rm=TRUE))
```

```{r}
get_day_ranks <- function(ranked.df, doi){
    day.ranks.df <- ranked.df %>% filter(day == doi) %>% filter( nchar(gene) < 10)
    day.ranks <- day.ranks.df$rankMed
    names(day.ranks) <- day.ranks.df$gene
    day.ranks
}
```

```{r}

day1.ranks <- get_day_ranks(ranked, 'd1')
day2.ranks <- get_day_ranks(ranked, 'd2')
day3.ranks <- get_day_ranks(ranked, 'd3')
day4.ranks <- get_day_ranks(ranked, 'd4')

```

```{r}
pathways <- scan("/data/10_21_pathway_enrichment/07-10-ko.gmt", what="", sep="\n")
pathways <- strsplit(pathways, "\t")
pathways <- lapply(pathways, function(z){ z[!is.na(z) & z != ""]})
names(pathways) <- sapply(pathways, `[[`, 1)
pathways <- lapply(pathways, `[`, c(-1))

```

```{r}
#length(day1.ranks)
#pathways

```



```{r}
fgseaRes.day1 <- fgsea(pathways = pathways,
                  stats    = day1.ranks,
                  minSize  = 5,
                  maxSize  = 500)

fgseaRes.day2 <- fgsea(pathways = pathways,
                  stats    = day2.ranks,
                  minSize  = 5,
                  maxSize  = 500)
fgseaRes.day3 <- fgsea(pathways = pathways,
                  stats    = day3.ranks,
                  minSize  = 5,
                  maxSize  = 500)
fgseaRes.day4 <- fgsea(pathways = pathways,
                  stats    = day4.ranks,
                  minSize  = 5,
                  maxSize  = 500)
```

```{r}
fwrite(fgseaRes.day1, "../../../data/10_21_pathway_enrichment/GSEA/fgseaRes.day1.csv")
fwrite(fgseaRes.day2, "../../../data/10_21_pathway_enrichment/GSEA/fgseaRes.day2.csv")
fwrite(fgseaRes.day3, "../../../data/10_21_pathway_enrichment/GSEA/fgseaRes.day3.csv")
fwrite(fgseaRes.day4, "../../../data/10_21_pathway_enrichment/GSEA/fgseaRes.day4.csv")
```




```{r}

rank_df <- read.csv('/Users/ansintsova/git_repos/nguyenb_tnseq/data/08_21/ranked_mean.csv', )
day1_ranks <- rank_df$rank_mean
names(day1_ranks) <- rank_df$locus_tag


```




```{r}
rank_df <- read.csv('/Users/ansintsova/git_repos/nguyenb_tnseq/code/notebooks/08_2021_pathway_enrichment/day2_ranked_mean.csv', )
day2_ranks <- rank_df$rank_mean
names(day2_ranks) <- rank_df$locus_tag
```

```{r}
rank_df <- read.csv('/Users/ansintsova/git_repos/nguyenb_tnseq/code/notebooks/08_2021_pathway_enrichment/day3_ranked_mean.csv', )
day3_ranks <- rank_df$rank_mean
names(day3_ranks) <- rank_df$locus_tag
```


```{r}
rank_df <- read.csv('/Users/ansintsova/git_repos/nguyenb_tnseq/code/notebooks/08_2021_pathway_enrichment/day4_ranked_mean.csv', )
day4_ranks <- rank_df$rank_mean
names(day4_ranks) <- rank_df$locus_tag
```


```{r}

#rank_df <- read.csv('/Users/ansintsova/git_repos/nguyenb_tnseq/code/notebooks/08_2021_pathway_enrichment/ranked_median.csv', )
#ranks <- rank_df$rank_median
#names(ranks) <- rank_df$locus_tag
#

```






```{r}
pathways <- scan("/Users/ansintsova/git_repos/nguyenb_tnseq/code/notebooks/08_2021_pathway_enrichment/15-09-sey.gmt", what="", sep="\n")
pathways <- strsplit(pathways, "\t")
pathways <- lapply(pathways, function(z){ z[!is.na(z) & z != ""]})
names(pathways) <- sapply(pathways, `[[`, 2)
pathways <- lapply(pathways, `[`, c(-1,-2,-3))


```

```{r}
fgseaRes1 <- fgsea(pathways = pathways,
                  stats    = day1_ranks,
                  minSize  = 5,
                  maxSize  = 500)
```
```{r}
topPathwaysDown <- fgseaRes1[ES < 0][head(order(pval), n=10), pathway]
plotGseaTable(pathways[topPathwaysDown], day1_ranks, fgseaRes1,
              gseaParam=0.5)
```
```{r}
fgseaRes2 <- fgsea(pathways = pathways,
                  stats    = day2_ranks,
                  minSize  = 5,
                  maxSize  = 500)
```
```{r}
topPathwaysDown <- fgseaRes2[ES < 0][head(order(pval), n=10), pathway]
plotGseaTable(pathways[topPathwaysDown], day2_ranks, fgseaRes2,
              gseaParam=0.5)
```

```{r}
fgseaRes3 <- fgsea(pathways = pathways,
                  stats    = day3_ranks,
                  minSize  = 5,
                  maxSize  = 500)
```

```{r}
topPathwaysDown <- fgseaRes3[ES < 0][head(order(pval), n=10), pathway]
plotGseaTable(pathways[topPathwaysDown], day3_ranks, fgseaRes3,
              gseaParam=0.5)
```

```{r}
fgseaRes4 <- fgsea(pathways = pathways,
                  stats    = day4_ranks,
                  minSize  = 5,
                  maxSize  = 500)
```

```{r}
topPathwaysDown <- fgseaRes4[ES < 0][head(order(pval), n=10), pathway]
plotGseaTable(pathways[topPathwaysDown], day4_ranks, fgseaRes4,
              gseaParam=0.5)
```
