root:
  local: /Users/ansintsova/polybox/Hardt/nguyenb/04_22_results
  server: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/Projects_NCCR/hardt/nguyenb/tnseq/scratch/04_22
mapDir: maps
countDir: counts
resultDir: results
libraryCountsDir: counts_by_library
sampleDataOriginal: complete_metadata.tsv
sampleData: 14-04-22-sample-data.csv
controlData: controls.txt
scratchDir:
  local: /Users/ansintsova/git_repos/nguyenb_tnseq/data/scratch
  server: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/04_22/tmp
