
root: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/Projects_NCCR/hardt/nguyenb/tnseq/scratch/nguyen_2024
analysis_dir: results
inoculum_dir: inoculum_analysis
map_dir: maps
sample_data_file: nguyen-2024-sample-data.csv
counts_dir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/final_counts/counts
out_dir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/final_counts/figures
gff_file: GCA_000210855.2.gff3.gz
mice_file: mice_per_library.csv.gz
string_enrichment_file: STRG0A50HSX.protein.enrichment.terms.v12.0.txt.gz
published_file: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/Projects_NCCR/hardt/nguyenb/tnseq/scratch/manuscript_data/nguyen_2020/nguyen_2020_results.csv


