
root: ../../nguyen_2024
analysis_dir: results
inoculum_dir: inoculum_analysis
map_dir: maps
sample_data_file: nguyen-2024-sample-data.csv
counts_dir: counts
out_dir: figures # does not exist, need to create
gff_file: GCA_000210855.2.gff3.gz
mice_file: mice_per_library.csv.gz
string_enrichment_file: STRG0A50HSX.protein.enrichment.terms.v12.0.txt.gz



