# Mapping
projectName: tnseq-mapping
dataDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/mapping_data
outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/08_21
samples: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/08_21/tnseq-mapping_sample.csv


## General settings

fq_fwd: _1.fq.gz
fq_rvr: _2.fq.gz
sanitise_name: true
name_delimiter: _
name_index: 3
merge_replicates: false # if set to false, 'sample' in sample.csv has to be a unique sample identifier

#Preprocessing
qc: yes
mink: 11
trimq: 14 # 37
mapq: 20
minlen: 45
adapters: 'adapters/adapters.fa'
phix: 'adapters/phix174_ill.ref.fa.gz'
fastqc: no

## Counting
#dataDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/raw
#metaDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/metadata
#outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/08_21
#sampleFile: configs/samples.txt
#
## References
#salmonella_db: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/chris/hardt/nguyenb/tnseq_mapping_2031/lib/Salmonella_genome_FQ312003.1_SL1344.fasta
#salmonella_gff: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/chris/hardt/nguyenb/tnseq_mapping_2031/lib/Salmonella_genome+plasmids.gff
#
#



