# Mapping
mapData: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/raw/mapping_data
mapOut: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/08_21
mapSamples: configs/mapSamples.txt


# Counting
dataDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/raw
metaDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/data/metadata
outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/08_21
sampleFile: configs/samples.txt

# References
salmonella_db: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/chris/hardt/nguyenb/tnseq_mapping_2031/lib/Salmonella_genome_FQ312003.1_SL1344.fasta
salmonella_gff: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/chris/hardt/nguyenb/tnseq_mapping_2031/lib/Salmonella_genome+plasmids.gff


# General settings

fq_fwd: _1.fq.gz
fq_rvr: _2.fq.gz

